osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "14"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:           #将会启动多个平台构建
  - windows
#  - linux
#  - osx   

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

install:
  - yarn install
script:
  - yarn release

branches:
  only:
    - master
